name: Python Workflow

on:
  push:
    branches:
      - main

jobs:
  scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setput python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'

      - name: Run the python code
        run: python test.py
